// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.21.12
// source: internal/contracts/aws.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AWSProviderConfig is the typed configuration for the iac.provider module
// provided by workflow-plugin-aws. All fields correspond to the map keys
// accepted by the legacy Initialize(ctx, map[string]any) path.
type AWSProviderConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// region is the AWS region (default: us-east-1).
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// access_key_id is the AWS access key ID for static credentials.
	AccessKeyId string `protobuf:"bytes,2,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	// secret_access_key is the AWS secret access key for static credentials.
	SecretAccessKey string `protobuf:"bytes,3,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	// ecs_cluster is the default ECS cluster name used by the ECS driver.
	EcsCluster    string `protobuf:"bytes,4,opt,name=ecs_cluster,json=ecsCluster,proto3" json:"ecs_cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AWSProviderConfig) Reset() {
	*x = AWSProviderConfig{}
	mi := &file_internal_contracts_aws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWSProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSProviderConfig) ProtoMessage() {}

func (x *AWSProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_aws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSProviderConfig.ProtoReflect.Descriptor instead.
func (*AWSProviderConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_aws_proto_rawDescGZIP(), []int{0}
}

func (x *AWSProviderConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AWSProviderConfig) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *AWSProviderConfig) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *AWSProviderConfig) GetEcsCluster() string {
	if x != nil {
		return x.EcsCluster
	}
	return ""
}

var File_internal_contracts_aws_proto protoreflect.FileDescriptor

var file_internal_contracts_aws_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x73, 0x2f, 0x61, 0x77, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73,
	0x2e, 0x61, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x9c, 0x01, 0x0a, 0x11, 0x41, 0x57, 0x53, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x63, 0x73, 0x5f, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x63, 0x73, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x6c, 0x6f, 0x6e, 0x65,
	0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2d, 0x61, 0x77, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x3b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_internal_contracts_aws_proto_rawDescOnce sync.Once
	file_internal_contracts_aws_proto_rawDescData []byte
)

func file_internal_contracts_aws_proto_rawDescGZIP() []byte {
	file_internal_contracts_aws_proto_rawDescOnce.Do(func() {
		file_internal_contracts_aws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_aws_proto_rawDesc), len(file_internal_contracts_aws_proto_rawDesc)))
	})
	return file_internal_contracts_aws_proto_rawDescData
}

var file_internal_contracts_aws_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_contracts_aws_proto_goTypes = []any{
	(*AWSProviderConfig)(nil), // 0: workflow.plugins.aws.v1.AWSProviderConfig
}
var file_internal_contracts_aws_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_contracts_aws_proto_init() }
func file_internal_contracts_aws_proto_init() {
	if File_internal_contracts_aws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_aws_proto_rawDesc), len(file_internal_contracts_aws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_aws_proto_goTypes,
		DependencyIndexes: file_internal_contracts_aws_proto_depIdxs,
		MessageInfos:      file_internal_contracts_aws_proto_msgTypes,
	}.Build()
	File_internal_contracts_aws_proto = out.File
	file_internal_contracts_aws_proto_goTypes = nil
	file_internal_contracts_aws_proto_depIdxs = nil
}
