// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/contracts/aws.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AWSProviderConfig is the typed configuration for the iac.provider module
// provided by workflow-plugin-aws. All fields correspond to the map keys
// accepted by the legacy Initialize(ctx, map[string]any) path.
type AWSProviderConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// region is the AWS region (default: us-east-1).
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// access_key_id is the AWS access key ID for static credentials.
	AccessKeyId string `protobuf:"bytes,2,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	// secret_access_key is the AWS secret access key for static credentials.
	SecretAccessKey string `protobuf:"bytes,3,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	// ecs_cluster is the default ECS cluster name used by the ECS driver.
	EcsCluster string `protobuf:"bytes,4,opt,name=ecs_cluster,json=ecsCluster,proto3" json:"ecs_cluster,omitempty"`
	// ecs_subnet_ids are default subnet IDs for provider-ephemeral ECS RunTask.
	EcsSubnetIds []string `protobuf:"bytes,5,rep,name=ecs_subnet_ids,json=ecsSubnetIds,proto3" json:"ecs_subnet_ids,omitempty"`
	// ecs_security_group_ids are default security groups for provider-ephemeral ECS RunTask.
	EcsSecurityGroupIds []string `protobuf:"bytes,6,rep,name=ecs_security_group_ids,json=ecsSecurityGroupIds,proto3" json:"ecs_security_group_ids,omitempty"`
	// ecs_task_execution_role_arn is the optional ECS task execution role ARN for runner jobs.
	EcsTaskExecutionRoleArn string `protobuf:"bytes,7,opt,name=ecs_task_execution_role_arn,json=ecsTaskExecutionRoleArn,proto3" json:"ecs_task_execution_role_arn,omitempty"`
	// ecs_runner_log_group is the CloudWatch Logs group used by runner jobs.
	EcsRunnerLogGroup string `protobuf:"bytes,8,opt,name=ecs_runner_log_group,json=ecsRunnerLogGroup,proto3" json:"ecs_runner_log_group,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AWSProviderConfig) Reset() {
	*x = AWSProviderConfig{}
	mi := &file_internal_contracts_aws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWSProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSProviderConfig) ProtoMessage() {}

func (x *AWSProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_aws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSProviderConfig.ProtoReflect.Descriptor instead.
func (*AWSProviderConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_aws_proto_rawDescGZIP(), []int{0}
}

func (x *AWSProviderConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AWSProviderConfig) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *AWSProviderConfig) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *AWSProviderConfig) GetEcsCluster() string {
	if x != nil {
		return x.EcsCluster
	}
	return ""
}

func (x *AWSProviderConfig) GetEcsSubnetIds() []string {
	if x != nil {
		return x.EcsSubnetIds
	}
	return nil
}

func (x *AWSProviderConfig) GetEcsSecurityGroupIds() []string {
	if x != nil {
		return x.EcsSecurityGroupIds
	}
	return nil
}

func (x *AWSProviderConfig) GetEcsTaskExecutionRoleArn() string {
	if x != nil {
		return x.EcsTaskExecutionRoleArn
	}
	return ""
}

func (x *AWSProviderConfig) GetEcsRunnerLogGroup() string {
	if x != nil {
		return x.EcsRunnerLogGroup
	}
	return ""
}

var File_internal_contracts_aws_proto protoreflect.FileDescriptor

const file_internal_contracts_aws_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/contracts/aws.proto\x12\x17workflow.plugins.aws.v1\"\xe6\x02\n" +
	"\x11AWSProviderConfig\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\"\n" +
	"\raccess_key_id\x18\x02 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x03 \x01(\tR\x0fsecretAccessKey\x12\x1f\n" +
	"\vecs_cluster\x18\x04 \x01(\tR\n" +
	"ecsCluster\x12$\n" +
	"\x0eecs_subnet_ids\x18\x05 \x03(\tR\fecsSubnetIds\x123\n" +
	"\x16ecs_security_group_ids\x18\x06 \x03(\tR\x13ecsSecurityGroupIds\x12<\n" +
	"\x1becs_task_execution_role_arn\x18\a \x01(\tR\x17ecsTaskExecutionRoleArn\x12/\n" +
	"\x14ecs_runner_log_group\x18\b \x01(\tR\x11ecsRunnerLogGroupBIZGgithub.com/GoCodeAlone/workflow-plugin-aws/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_aws_proto_rawDescOnce sync.Once
	file_internal_contracts_aws_proto_rawDescData []byte
)

func file_internal_contracts_aws_proto_rawDescGZIP() []byte {
	file_internal_contracts_aws_proto_rawDescOnce.Do(func() {
		file_internal_contracts_aws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_aws_proto_rawDesc), len(file_internal_contracts_aws_proto_rawDesc)))
	})
	return file_internal_contracts_aws_proto_rawDescData
}

var file_internal_contracts_aws_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_contracts_aws_proto_goTypes = []any{
	(*AWSProviderConfig)(nil), // 0: workflow.plugins.aws.v1.AWSProviderConfig
}
var file_internal_contracts_aws_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_contracts_aws_proto_init() }
func file_internal_contracts_aws_proto_init() {
	if File_internal_contracts_aws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_aws_proto_rawDesc), len(file_internal_contracts_aws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_aws_proto_goTypes,
		DependencyIndexes: file_internal_contracts_aws_proto_depIdxs,
		MessageInfos:      file_internal_contracts_aws_proto_msgTypes,
	}.Build()
	File_internal_contracts_aws_proto = out.File
	file_internal_contracts_aws_proto_goTypes = nil
	file_internal_contracts_aws_proto_depIdxs = nil
}
