// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/contracts/aws_plan2.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AWSCredentialsBlock mirrors the YAML `credentials:` sub-block the
// plan-2 modules accept. The `type` field — when non-empty — selects one
// of "static" | "env" | "profile" | "role_arn"; consumed by
// awscreds.BuildAWSConfig (see internal/awscreds/awscreds.go).
type AWSCredentialsBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type selects the credential source path. One of:
	//
	//	"static"   — inline access_key / secret_key (default when keys present)
	//	"env"      — aws-sdk-go-v2 default credential chain
	//	"profile"  — shared-config profile via WithSharedConfigProfile
	//	"role_arn" — STS AssumeRole on top of base credentials
	//
	// Empty string = same as "env" (default chain).
	Type         string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	AccessKey    string `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey    string `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	SessionToken string `protobuf:"bytes,4,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	// role_arn / external_id / session_name — honored only when type=="role_arn".
	RoleArn    string `protobuf:"bytes,5,opt,name=role_arn,json=roleArn,proto3" json:"role_arn,omitempty"`
	ExternalId string `protobuf:"bytes,6,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// profile — honored only when type=="profile".
	Profile       string `protobuf:"bytes,7,opt,name=profile,proto3" json:"profile,omitempty"`
	SessionName   string `protobuf:"bytes,8,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AWSCredentialsBlock) Reset() {
	*x = AWSCredentialsBlock{}
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWSCredentialsBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSCredentialsBlock) ProtoMessage() {}

func (x *AWSCredentialsBlock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSCredentialsBlock.ProtoReflect.Descriptor instead.
func (*AWSCredentialsBlock) Descriptor() ([]byte, []int) {
	return file_internal_contracts_aws_plan2_proto_rawDescGZIP(), []int{0}
}

func (x *AWSCredentialsBlock) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AWSCredentialsBlock) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *AWSCredentialsBlock) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *AWSCredentialsBlock) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AWSCredentialsBlock) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *AWSCredentialsBlock) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *AWSCredentialsBlock) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *AWSCredentialsBlock) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

// AWSCredentialsConfig is the typed configuration for the aws.credentials
// standalone module. The module registers the parsed credentials block in
// the process-local credref registry under the module's own name so
// sibling storage.s3 / step.s3_upload modules can reference it via
// `credentials_ref:`.
type AWSCredentialsConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// region is the AWS region the credentials are scoped to (used as the
	// default region when sibling modules don't override).
	Region        string               `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Credentials   *AWSCredentialsBlock `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AWSCredentialsConfig) Reset() {
	*x = AWSCredentialsConfig{}
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWSCredentialsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSCredentialsConfig) ProtoMessage() {}

func (x *AWSCredentialsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSCredentialsConfig.ProtoReflect.Descriptor instead.
func (*AWSCredentialsConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_aws_plan2_proto_rawDescGZIP(), []int{1}
}

func (x *AWSCredentialsConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AWSCredentialsConfig) GetCredentials() *AWSCredentialsBlock {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// S3StorageConfig is the typed configuration for the storage.s3 module.
// The module exposes Put/Get/Delete object operations against the named
// bucket. Credentials come from EITHER the inline `credentials:` block OR
// `credentials_ref:` (a sibling aws.credentials module name) — inline
// wins when both are supplied.
type S3StorageConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bucket is the S3 bucket name (REQUIRED).
	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// region is the AWS region; if set, overrides the referenced
	// credentials' region.
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// endpoint is an optional custom S3 endpoint URL (MinIO / LocalStack).
	// When set, the client uses path-style addressing.
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// credentials_ref names an aws.credentials module to look up in the
	// process-local credref registry. Mutually exclusive with `credentials`;
	// inline credentials win when both are supplied.
	CredentialsRef string               `protobuf:"bytes,4,opt,name=credentials_ref,json=credentialsRef,proto3" json:"credentials_ref,omitempty"`
	Credentials    *AWSCredentialsBlock `protobuf:"bytes,5,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S3StorageConfig) Reset() {
	*x = S3StorageConfig{}
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3StorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3StorageConfig) ProtoMessage() {}

func (x *S3StorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3StorageConfig.ProtoReflect.Descriptor instead.
func (*S3StorageConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_aws_plan2_proto_rawDescGZIP(), []int{2}
}

func (x *S3StorageConfig) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3StorageConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3StorageConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3StorageConfig) GetCredentialsRef() string {
	if x != nil {
		return x.CredentialsRef
	}
	return ""
}

func (x *S3StorageConfig) GetCredentials() *AWSCredentialsBlock {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// S3UploadStepConfig is the typed configuration for the step.s3_upload
// pipeline step. The step uploads a base64-encoded body from the pipeline
// context to S3 and returns S3UploadStepOutput.
type S3UploadStepConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bucket is the S3 bucket name (REQUIRED).
	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// region is the AWS region (REQUIRED).
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// endpoint is an optional custom S3 endpoint URL (MinIO / LocalStack).
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// key is a Go text/template-rendered object key. Supports
	// `{{ .field }}` substitution from the pipeline-context data and a
	// `{{ uuid }}` helper.
	Key string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// body_from is the dot-path into the pipeline context (current +
	// step outputs under the "steps" key) that resolves to a
	// base64-encoded body string.
	BodyFrom string `protobuf:"bytes,5,opt,name=body_from,json=bodyFrom,proto3" json:"body_from,omitempty"`
	// content_type is the static Content-Type for the uploaded object.
	// Used when content_type_from is empty or unresolvable.
	ContentType string `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// content_type_from is a dot-path into the pipeline context that
	// resolves to a Content-Type string. Beats content_type when present.
	ContentTypeFrom string `protobuf:"bytes,7,opt,name=content_type_from,json=contentTypeFrom,proto3" json:"content_type_from,omitempty"`
	// credentials_ref / credentials — same semantics as S3StorageConfig.
	CredentialsRef string               `protobuf:"bytes,8,opt,name=credentials_ref,json=credentialsRef,proto3" json:"credentials_ref,omitempty"`
	Credentials    *AWSCredentialsBlock `protobuf:"bytes,9,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S3UploadStepConfig) Reset() {
	*x = S3UploadStepConfig{}
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3UploadStepConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3UploadStepConfig) ProtoMessage() {}

func (x *S3UploadStepConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3UploadStepConfig.ProtoReflect.Descriptor instead.
func (*S3UploadStepConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_aws_plan2_proto_rawDescGZIP(), []int{3}
}

func (x *S3UploadStepConfig) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3UploadStepConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3UploadStepConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3UploadStepConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *S3UploadStepConfig) GetBodyFrom() string {
	if x != nil {
		return x.BodyFrom
	}
	return ""
}

func (x *S3UploadStepConfig) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *S3UploadStepConfig) GetContentTypeFrom() string {
	if x != nil {
		return x.ContentTypeFrom
	}
	return ""
}

func (x *S3UploadStepConfig) GetCredentialsRef() string {
	if x != nil {
		return x.CredentialsRef
	}
	return ""
}

func (x *S3UploadStepConfig) GetCredentials() *AWSCredentialsBlock {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// S3UploadStepOutput is the typed output map step.s3_upload returns.
type S3UploadStepOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// url is the virtual-hosted-style URL of the uploaded object
	// (`https://<bucket>.s3.<region>.amazonaws.com/<key>`), or, when a
	// custom endpoint is configured, `<endpoint>/<bucket>/<key>`.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// key is the rendered S3 object key after template substitution.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// bucket is the S3 bucket name the object was uploaded to.
	Bucket        string `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3UploadStepOutput) Reset() {
	*x = S3UploadStepOutput{}
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3UploadStepOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3UploadStepOutput) ProtoMessage() {}

func (x *S3UploadStepOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3UploadStepOutput.ProtoReflect.Descriptor instead.
func (*S3UploadStepOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_aws_plan2_proto_rawDescGZIP(), []int{4}
}

func (x *S3UploadStepOutput) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *S3UploadStepOutput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *S3UploadStepOutput) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

// S3DownloadStepConfig is the typed configuration for the step.s3_download
// pipeline step. The step fetches an object through storage.s3 and returns a
// base64-encoded body under output_name, plus content/artifact metadata.
type S3DownloadStepConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bucket is the S3 bucket name (REQUIRED).
	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// region is the AWS region. Required when bucket is set.
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// endpoint is an optional custom S3 endpoint URL (MinIO / LocalStack).
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// storage_ref is the logical storage.s3 module reference for host-level
	// orchestration metadata. The current step still requires bucket/region and
	// uses this as metadata rather than as an in-process module lookup.
	StorageRef string `protobuf:"bytes,4,opt,name=storage_ref,json=storageRef,proto3" json:"storage_ref,omitempty"`
	// key is a Go text/template-rendered object key. Supports the same template
	// surface as step.s3_upload.
	Key string `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	// output_name is an optional alias for the base64 body output. The canonical
	// strict-contract field "body" is always emitted.
	OutputName string `protobuf:"bytes,6,opt,name=output_name,json=outputName,proto3" json:"output_name,omitempty"`
	// artifact is the declared artifact name for compute-provider handoff.
	Artifact       string               `protobuf:"bytes,7,opt,name=artifact,proto3" json:"artifact,omitempty"`
	ContentType    string               `protobuf:"bytes,8,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CredentialsRef string               `protobuf:"bytes,9,opt,name=credentials_ref,json=credentialsRef,proto3" json:"credentials_ref,omitempty"`
	Credentials    *AWSCredentialsBlock `protobuf:"bytes,10,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S3DownloadStepConfig) Reset() {
	*x = S3DownloadStepConfig{}
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3DownloadStepConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3DownloadStepConfig) ProtoMessage() {}

func (x *S3DownloadStepConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3DownloadStepConfig.ProtoReflect.Descriptor instead.
func (*S3DownloadStepConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_aws_plan2_proto_rawDescGZIP(), []int{5}
}

func (x *S3DownloadStepConfig) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3DownloadStepConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3DownloadStepConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3DownloadStepConfig) GetStorageRef() string {
	if x != nil {
		return x.StorageRef
	}
	return ""
}

func (x *S3DownloadStepConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *S3DownloadStepConfig) GetOutputName() string {
	if x != nil {
		return x.OutputName
	}
	return ""
}

func (x *S3DownloadStepConfig) GetArtifact() string {
	if x != nil {
		return x.Artifact
	}
	return ""
}

func (x *S3DownloadStepConfig) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *S3DownloadStepConfig) GetCredentialsRef() string {
	if x != nil {
		return x.CredentialsRef
	}
	return ""
}

func (x *S3DownloadStepConfig) GetCredentials() *AWSCredentialsBlock {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type S3DownloadStepOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	ContentRef    string                 `protobuf:"bytes,4,opt,name=content_ref,json=contentRef,proto3" json:"content_ref,omitempty"`
	StorageRef    string                 `protobuf:"bytes,5,opt,name=storage_ref,json=storageRef,proto3" json:"storage_ref,omitempty"`
	Artifact      string                 `protobuf:"bytes,6,opt,name=artifact,proto3" json:"artifact,omitempty"`
	ContentType   string                 `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ContentSize   int64                  `protobuf:"varint,8,opt,name=content_size,json=contentSize,proto3" json:"content_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3DownloadStepOutput) Reset() {
	*x = S3DownloadStepOutput{}
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3DownloadStepOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3DownloadStepOutput) ProtoMessage() {}

func (x *S3DownloadStepOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_aws_plan2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3DownloadStepOutput.ProtoReflect.Descriptor instead.
func (*S3DownloadStepOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_aws_plan2_proto_rawDescGZIP(), []int{6}
}

func (x *S3DownloadStepOutput) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *S3DownloadStepOutput) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3DownloadStepOutput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *S3DownloadStepOutput) GetContentRef() string {
	if x != nil {
		return x.ContentRef
	}
	return ""
}

func (x *S3DownloadStepOutput) GetStorageRef() string {
	if x != nil {
		return x.StorageRef
	}
	return ""
}

func (x *S3DownloadStepOutput) GetArtifact() string {
	if x != nil {
		return x.Artifact
	}
	return ""
}

func (x *S3DownloadStepOutput) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *S3DownloadStepOutput) GetContentSize() int64 {
	if x != nil {
		return x.ContentSize
	}
	return 0
}

var File_internal_contracts_aws_plan2_proto protoreflect.FileDescriptor

const file_internal_contracts_aws_plan2_proto_rawDesc = "" +
	"\n" +
	"\"internal/contracts/aws_plan2.proto\x12\x17workflow.plugins.aws.v1\"\x85\x02\n" +
	"\x13AWSCredentialsBlock\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"access_key\x18\x02 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x03 \x01(\tR\tsecretKey\x12#\n" +
	"\rsession_token\x18\x04 \x01(\tR\fsessionToken\x12\x19\n" +
	"\brole_arn\x18\x05 \x01(\tR\aroleArn\x12\x1f\n" +
	"\vexternal_id\x18\x06 \x01(\tR\n" +
	"externalId\x12\x18\n" +
	"\aprofile\x18\a \x01(\tR\aprofile\x12!\n" +
	"\fsession_name\x18\b \x01(\tR\vsessionName\"~\n" +
	"\x14AWSCredentialsConfig\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12N\n" +
	"\vcredentials\x18\x02 \x01(\v2,.workflow.plugins.aws.v1.AWSCredentialsBlockR\vcredentials\"\xd6\x01\n" +
	"\x0fS3StorageConfig\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12'\n" +
	"\x0fcredentials_ref\x18\x04 \x01(\tR\x0ecredentialsRef\x12N\n" +
	"\vcredentials\x18\x05 \x01(\v2,.workflow.plugins.aws.v1.AWSCredentialsBlockR\vcredentials\"\xd7\x02\n" +
	"\x12S3UploadStepConfig\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1b\n" +
	"\tbody_from\x18\x05 \x01(\tR\bbodyFrom\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12*\n" +
	"\x11content_type_from\x18\a \x01(\tR\x0fcontentTypeFrom\x12'\n" +
	"\x0fcredentials_ref\x18\b \x01(\tR\x0ecredentialsRef\x12N\n" +
	"\vcredentials\x18\t \x01(\v2,.workflow.plugins.aws.v1.AWSCredentialsBlockR\vcredentials\"P\n" +
	"\x12S3UploadStepOutput\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\"\xee\x02\n" +
	"\x14S3DownloadStepConfig\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vstorage_ref\x18\x04 \x01(\tR\n" +
	"storageRef\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x12\x1f\n" +
	"\voutput_name\x18\x06 \x01(\tR\n" +
	"outputName\x12\x1a\n" +
	"\bartifact\x18\a \x01(\tR\bartifact\x12!\n" +
	"\fcontent_type\x18\b \x01(\tR\vcontentType\x12'\n" +
	"\x0fcredentials_ref\x18\t \x01(\tR\x0ecredentialsRef\x12N\n" +
	"\vcredentials\x18\n" +
	" \x01(\v2,.workflow.plugins.aws.v1.AWSCredentialsBlockR\vcredentials\"\xf8\x01\n" +
	"\x14S3DownloadStepOutput\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x1f\n" +
	"\vcontent_ref\x18\x04 \x01(\tR\n" +
	"contentRef\x12\x1f\n" +
	"\vstorage_ref\x18\x05 \x01(\tR\n" +
	"storageRef\x12\x1a\n" +
	"\bartifact\x18\x06 \x01(\tR\bartifact\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\x12!\n" +
	"\fcontent_size\x18\b \x01(\x03R\vcontentSizeBIZGgithub.com/GoCodeAlone/workflow-plugin-aws/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_aws_plan2_proto_rawDescOnce sync.Once
	file_internal_contracts_aws_plan2_proto_rawDescData []byte
)

func file_internal_contracts_aws_plan2_proto_rawDescGZIP() []byte {
	file_internal_contracts_aws_plan2_proto_rawDescOnce.Do(func() {
		file_internal_contracts_aws_plan2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_aws_plan2_proto_rawDesc), len(file_internal_contracts_aws_plan2_proto_rawDesc)))
	})
	return file_internal_contracts_aws_plan2_proto_rawDescData
}

var file_internal_contracts_aws_plan2_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_contracts_aws_plan2_proto_goTypes = []any{
	(*AWSCredentialsBlock)(nil),  // 0: workflow.plugins.aws.v1.AWSCredentialsBlock
	(*AWSCredentialsConfig)(nil), // 1: workflow.plugins.aws.v1.AWSCredentialsConfig
	(*S3StorageConfig)(nil),      // 2: workflow.plugins.aws.v1.S3StorageConfig
	(*S3UploadStepConfig)(nil),   // 3: workflow.plugins.aws.v1.S3UploadStepConfig
	(*S3UploadStepOutput)(nil),   // 4: workflow.plugins.aws.v1.S3UploadStepOutput
	(*S3DownloadStepConfig)(nil), // 5: workflow.plugins.aws.v1.S3DownloadStepConfig
	(*S3DownloadStepOutput)(nil), // 6: workflow.plugins.aws.v1.S3DownloadStepOutput
}
var file_internal_contracts_aws_plan2_proto_depIdxs = []int32{
	0, // 0: workflow.plugins.aws.v1.AWSCredentialsConfig.credentials:type_name -> workflow.plugins.aws.v1.AWSCredentialsBlock
	0, // 1: workflow.plugins.aws.v1.S3StorageConfig.credentials:type_name -> workflow.plugins.aws.v1.AWSCredentialsBlock
	0, // 2: workflow.plugins.aws.v1.S3UploadStepConfig.credentials:type_name -> workflow.plugins.aws.v1.AWSCredentialsBlock
	0, // 3: workflow.plugins.aws.v1.S3DownloadStepConfig.credentials:type_name -> workflow.plugins.aws.v1.AWSCredentialsBlock
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_contracts_aws_plan2_proto_init() }
func file_internal_contracts_aws_plan2_proto_init() {
	if File_internal_contracts_aws_plan2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_aws_plan2_proto_rawDesc), len(file_internal_contracts_aws_plan2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_aws_plan2_proto_goTypes,
		DependencyIndexes: file_internal_contracts_aws_plan2_proto_depIdxs,
		MessageInfos:      file_internal_contracts_aws_plan2_proto_msgTypes,
	}.Build()
	File_internal_contracts_aws_plan2_proto = out.File
	file_internal_contracts_aws_plan2_proto_goTypes = nil
	file_internal_contracts_aws_plan2_proto_depIdxs = nil
}
